//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCrawler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentLink
    {
        public System.Guid Id { get; set; }
        public string Url { get; set; }
        public string HtmlContent { get; set; }
        public string TextContent { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<int> Depth { get; set; }
        public string ContentType { get; set; }
        public Nullable<System.TimeSpan> DownloadTime { get; set; }
        public string Title { get; set; }
        public string StatusDescription { get; set; }
        public string Server { get; set; }
        public string ContentEncoding { get; set; }
        public string Headers { get; set; }
        public string CharacterSet { get; set; }
        public string StatusCode { get; set; }
        public string Method { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public Nullable<bool> IsFromCache { get; set; }
        public Nullable<System.DateTime> WebLastUpdate { get; set; }
        public string WebAuthors { get; set; }
    }
}
