//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCrawler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public System.Guid Id { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public Nullable<decimal> FileSize { get; set; }
        public Nullable<System.DateTime> DownloadTime { get; set; }
        public string Url { get; set; }
        public Nullable<System.Guid> UrlId { get; set; }
    }
}
