//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCrawler.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class iCrawlerEntities : DbContext
    {
        public iCrawlerEntities()
            : base("name=iCrawlerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Url> Urls { get; set; }
        public DbSet<WebContent> WebContents { get; set; }
        public DbSet<CurrentLink> CurrentLinks { get; set; }
        public DbSet<Document> Documents { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<HistoryLink> HistoryLinks { get; set; }
        public DbSet<UrlOfUser> UrlOfUsers { get; set; }
    }
}
