//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCrawler.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebContent
    {
        public System.Guid Id { get; set; }
        public string Url { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> TimeDownloaded { get; set; }
        public Nullable<bool> IsNotify { get; set; }
        public Nullable<System.DateTime> TimeNotify { get; set; }
        public Nullable<bool> NotifyStatus { get; set; }
        public string KeyWords { get; set; }
        public string Title { get; set; }
        public string HtmlContent { get; set; }
    }
}
