//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCrawler.Models.ChuyenLy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public System.Guid Id { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.Guid> CategoryId { get; set; }
        public Nullable<int> CountViews { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<bool> IsReviewed { get; set; }
        public Nullable<System.DateTime> ReviewedDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<bool> IsReturned { get; set; }
        public Nullable<System.DateTime> ReturnedDate { get; set; }
        public string Tags { get; set; }
        public string ApprovedBy { get; set; }
        public string AvatarPath { get; set; }
    }
}
