//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCrawlerMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Url
    {
        public System.Guid Id { get; set; }
        public string Url1 { get; set; }
        public string Description { get; set; }
        public string Times { get; set; }
        public string HelpText { get; set; }
    }
}
