//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCrawlerMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlOfUser
    {
        public int UserId { get; set; }
        public Nullable<System.Guid> UrlId { get; set; }
        public string Times { get; set; }
        public string Keywords { get; set; }
        public string Emails { get; set; }
    }
}
